# Generated by Django 2.0.6 on 2018-06-28 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.AddField(
            model_name='entry',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 28, 7, 31, 24, 33374, tzinfo=utc), verbose_name='start date'),
            preserve_default=False,
        ),
    ]
