# Generated by Django 2.0.6 on 2018-06-28 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20180628_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 7, 33, 23, 687310, tzinfo=utc), verbose_name='end date'),
            preserve_default=False,
        ),
    ]
