# Generated by Django 2.0.6 on 2018-06-29 00:43

from django.db import migrations, models
import personal.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_entry_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='position',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(blank=True, null=True, upload_to=personal.models.get_upload_path),
        ),
    ]
