# Generated by Django 2.0.6 on 2018-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20180628_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Work Experience', 'Work Experience'), ('Projects', 'Projects'), ('Ya', 'Ya')], max_length=140),
        ),
    ]
