# Generated by Django 2.0.6 on 2018-07-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default='HELLO', max_length=30),
            preserve_default=False,
        ),
    ]
