# Generated by Django 2.0.6 on 2018-07-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_home_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Contact', 'Contact'), ('Home', 'Home')], max_length=140)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Work Experience', 'Work Experience'), ('Projects', 'Projects')], max_length=140),
        ),
    ]
